dataset__add_noise: false
dataset__base_version: 1
dataset__k_fold: 1
dataset__loss: default
dataset__name: simpson
dataset__num_samples: 25000
dataset__root: ../Data
dataset__scale: default
dataset__sem_name: non-linear
dataset__shuffle_train: true
dataset__single_split: false
dataset__splits:
- 0.8
- 0.1
- 0.1
dataset__type: torch
dataset__use_edge_attr: false
device: auto
early_stopping__activate: false
early_stopping__min_delta: 0.0
early_stopping__patience: 3
early_stopping__verbose: false
gnn2__aggregators:
- sum
- mean
- min
- max
- std
gnn2__dim_inner: 64
gnn2__eps: 0.0
gnn2__heads: 1
gnn2__num_layers: 1
gnn2__num_layers_post: 1
gnn2__num_layers_pre: 1
gnn2__post_layers: 1
gnn2__pre_layers: 1
gnn2__scalers:
- identity
- amplification
- attenuation
- linear
- inverse_linear
gnn2__stage_type: skipsum
gnn2__towers: 1
gnn2__train_eps: false
gnn__aggregators:
- sum
- mean
- min
- max
- std
gnn__dim_inner: 64
gnn__eps: 0.0
gnn__heads: 1
gnn__num_layers: 1
gnn__num_layers_post: 1
gnn__num_layers_pre: 1
gnn__post_layers: 1
gnn__pre_layers: 1
gnn__scalers:
- identity
- amplification
- attenuation
- linear
- inverse_linear
gnn__stage_type: skipsum
gnn__towers: 1
gnn__train_eps: false
model__act: elu
model__adjacency: true
model__base_distr: normal
model__base_to_data: false
model__beta: 1.0
model__dim_inner:
- 32
- 32
- 32
model__distr_u: laplace
model__distr_x: normal
model__dropout: 0.0
model__has_bn: false
model__init: null
model__lambda_: 0.01
model__latent_dim: 4
model__layer_name: maf
model__learn_base: false
model__name: causal_nf
model__net_name: mlp
model__num_layers: 1
model__objective: elbo
model__parity: false
model__plot: false
model__scale: false
model__scale_base: false
model__shift_base: false
optim__base_lr: 0.001
optim__beta_1: 0.9
optim__beta_2: 0.999
optim__cooldown: 0
optim__factor: 0.95
optim__gamma: 0.99
optim__mode: min
optim__momentum: 0.0
optim__optimizer: adam
optim__patience: 60
optim__scheduler: plateau
optim__step_size: 100
optim__weight_decay: 0.0
param_count: 2536
root_dir: output_testing
seed: 2
train__auto_lr_find: false
train__auto_scale_batch_size: false
train__batch_size: 4096
train__enable_progress_bar: true
train__inference_mode: false
train__kl: forward
train__limit_train_batches: null
train__limit_val_batches: null
train__max_epochs: 1000
train__max_time: 00:01:00:00
train__model_checkpoint: true
train__num_workers: 0
train__profiler: null
train__regularize: false
